### ISSUE TITLE
selectedOptions isn't universally supported

### ISSUE THREAD

**Issue by npiasecki** [smartystreets/jquery.liveaddress#20]
When the state field is a dropdown menu, then then check on line 1859 fails in Internet Explorer 11 as `selectedOptions` doesn't exist there:

    stateText = fields.state.dom.selectedOptions[0].text;

In my case I just flipped it to a jQuery call to abstract away the differences:

    stateText = $(fields.state.dom).val();

... I know the documentation recommends using a text field, but hope this helps anyone stubbornly clinging to a dropdown

**Comment by camigreenall** [comment]
I just updated this to still use the text and be compatible with IE 11.
```
stateText = fields.state.dom.selectedOptions[0].text;
```
changed to
```
stateText = fields.state.dom.options[fields.state.dom.selectedIndex].text;
```

It is necessary to use the text from the state dropdown because the text is guaranteed (more often than the value) to match up to a state abbreviation or full name. Values can be set to whatever and will only sometimes be set as state abbreviation or full name.

Thanks for catching this bug!
