### ISSUE TITLE
JavaScript Error: Undefined is not an object

### ISSUE THREAD

**Issue by tamarazuk** [smartystreets/jquery.liveaddress#32]
We're testing an upgrade from version 2.5 to 2.8 and we've been greeted with the following JS error:

```
TypeError: undefined is not an object (evaluating 'K.state.dom[K.state.dom.selectedIndex].text')
```

[this line](https://github.com/smartystreets/jquery.liveaddress/blob/master/src/jquery.liveaddress.js#L2208) should probably check if `fields.state.dom[fields.state.dom.selectedIndex]` is defined and an object before trying to access its property

Thanks!

**Comment by camiblanch** [comment]
@tamarazuk I'm going to push your suggested change, but I think the reason you are getting that error is because the state dropdown is not in standard form. If you are missing states from the dropdown list it will cause the behavior you describe. With the change I am pushing it will stop the error from showing up, but I can't guarantee that you won't have issues with the state dropdown you are testing with in the future.
