### ISSUE TITLE
Recent change breaks internationalization 

### ISSUE THREAD

**Issue by tamarazuk** [smartystreets/jquery.liveaddress#35]
The change introduced in SHA 4b77699995dcd3e16d7c05c20a701df649af928b breaks the ability to translate option texts to different languages. 

The previous behaviour of checking the value selected rather than the text is less susceptible to issues when unexpected texts are displayed. I would suggesting checking against both the text and the value to ensure the library retains compatibility with sites in languages other than English

The unexpected change also broke our WooCommerce integration as it displays the country as `United States (US)` - [see here](https://github.com/woothemes/woocommerce/blob/728c2f576efb642f4ca3d3bdaa107287a250942f/i18n/countries.php#L249). We will release a **temporary** change that ensures this text reads `United States` exactly until jquery.liveaddress releases a fix.

**Comment by camiblanch** [comment]
I have talked to our support team regarding this issue and have come to a conclusion. We cannot support country names in languages that are not English. The best way to support country names that are not in English is to (1) wait until our international plugin is finished (no release data yet) or (2) fork the github code and customize it for your use case. We have had issues with looking at the `value` parameter of dropdown options because they are not as reliable as the actual text value. I am sorry this fix has caused issues in your use case. However, I will add `United States (US)` to the list of recognized values.

**Comment by camiblanch** [comment]
Please let me know if you have other US values you would like to add to our recognized list or if you have any other concerns or suggestions for improving the LiveAddress plugin. We appreciate your input.
