### ISSUE TITLE
autoVerify triggers in selection fields on keypress

### ISSUE THREAD

**Issue by AdJesumPerMariam** [smartystreets/jquery.liveaddress#61]
When inputting an address with autoVerify on it triggers the verification on keypress in selection type fields. This is bad for UX because a customer could mean to enter "Kentucky" but when they hit K then "Kanas" will be selected and auto-verify will be triggered on that. A workaround is to disable the autoVerify setting.

Demo: https://imgur.com/a/iAEoO

**Comment by camiblanch** [comment]
The type of dropdown that you are using is not support by our jQuery plugin. You should use a regular input field or a dropdown instead of a hybrid combo. You can read more about what type of dropdown selectors are compatible  to use with the plugin [here](https://smartystreets.com/docs/plugins/website/troubleshooting#select).

**Comment by sreed-dci** [comment]
Hm. This can be reproduced here: https://jsfiddle.net/y6w8b399/680/
This fiddle uses only a regular select field.

**Comment by camiblanch** [comment]
Hmm. I see what you mean. If users want Kentucky, and they are choosing it by typing, the browser will signal a change event as soon as they choose Kansas. It would be difficult to change the plugin to work for your case and still work for the case of regular input fields. I think there are a couple of possible workarounds. First, you could set `autoVerify` to `false`; then users could select states from the dropdown menu and just click the submit button, and then verification would happen. Or you could instruct customers to choose the state using the mouse. Or you could use a regular input field instead of a drop-down menu. Is that helpful?

**Comment by sreed-dci** [comment]
Yeah, I turned off auto-verification. I figured I would submit it to you because it seems like maybe verification on keypress for select fields should be turned off, or only trigger on blur.

**Comment by camiblanch** [comment]
I like your suggestion of changing it to be onblur instead of keypress. I'll look into seeing if this would negatively effect the plugin by making this change

**Comment by camiblanch** [comment]
Okay so first I had an idea to only fire the `AddressChanged` event in the plugin on select boxes if the jquery `change` event was fired followed by a `blur` or listen on `blur` and keep some kind of state to see if the field has actually changed. The problem occurs when users select the state by clicking on it from the list. They have made a choice, but they haven't moved to the next field so the plugin's `AddressChanged` event never gets fired. Thoughts?

**Comment by sreed-dci** [comment]
I'll be sure to look at this next week. Have a good weekend !

**Comment by cbuchert** [comment]
@AdJesumPerMariam We haven't heard from you in a while. Should I keep this issue open?

**Comment by AdJesumPerMariam** [comment]
@cbuchert I haven't had time to look into this and unfortunately, I won't. I think it is an issue though so I suggest that it is looked into by your team. Thanks!

**Comment by cbuchert** [comment]
This plugin has been deprecated, so there will be no continued development on the project. If you're looking for a more flexible JavaScript solution for integration with SmartyStreets APIs, check out the [SmartyStreets JavaScript SDK](https://github.com/smartystreets/smartystreets-javascript-sdk).
