### ISSUE TITLE
Secondary address formatting

### ISSUE THREAD

**Issue by HammerData** [smartystreets/jquery.liveaddress#69]
Is there a way to prevent the plugin from adding a space after the # on addresses with a unit number?

Example:
**123 Some St #456** becomes **123 Some St # 456**

**Comment by camiblanch** [comment]
The space between `#` and the unit number comes directly from the US Street API. You can see an example of that [here](https://smartystreets.com/products/apis/us-street-api?auth-id=21102174564513388&candidates=10&street=3214%20N%20University%20Ave%20%23409&city=provo&state=ut&method=GET). 

If you wanted to you could try manipulating the data when it comes back from the API and construct the secondary number format yourself by looking at the [`secondary_designator`](https://smartystreets.com/docs/cloud/us-street-api#secondarydesignator) and [`secondary_number`](https://smartystreets.com/docs/cloud/us-street-api#secondarynumber). You will have to be careful however because the secondary number is part of [`delivery_line_1`](https://smartystreets.com/docs/cloud/us-street-api#deliveryline1) which is used by the plugin to automatically populate the field you map to `address1` in the plugin configuration.

Does that help?

**Comment by HammerData** [comment]
Yep. I'll try to catch it on the way into the database. Thanks!
