### ISSUE TITLE
Allow 'Customisability' Of Country Name In Forms

### ISSUE THREAD

**Issue by tundebabzy** [smartystreets/jquery.liveaddress#76]
We are presently having issues when using liveaddress in our ERP. When an `Address` isDomestic`, liveaddress automatically 'USA' into the input field for country in the given form. The problem is, we internally use 'United States'. The result is that the field starts out as 'United States', changes to 'USA'. We can't accept 'USA' so we have to change it back to 'United States'.

Since 'United States of America', 'USA', 'US', 'U.S', 'United States' and even 'America' are all correct, I think users should be able to configure what country name should be written to the form.

I can open a PR that makes this possible by adding a config option called maybe `countryName` which defaults to USA. liveaddress can then use this option when writing the country name to the form while it still uses 'USA' internally.

What do you think?

**Comment by camiblanch** [comment]
I can see how this would be beneficial to you if your application requires the full-text country name.  Since it is not something that is oft-requested (in the last 6 years) we aren't planning to build it into our supported version of this tool.  You could certainly fork it and add the functionality that you are looking for.
